---
languages:
 - ruby
rules:
  test_infection:
    except:
      - 'lib/page_magic/exceptions*'
  missing_class_documentation:
    except:
      - 'lib/page_magic/element/query.rb'
      - 'lib/page_magic/element/selector.rb'
      - 'lib/page_magic/element/method_observer.rb'
      - 'lib/page_magic/element.rb'
